apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -v2
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: proxy-cm
  literals:
    - VERSION="v2"
commonLabels:
  app: proxy
  version: v2
resources:
  - deployment.yaml
